<?php

// Copy and edit this code in your wp-config file or in a mu-plugin

define('WP_UNHOOKED_CONFIG', [
    'disable-admin-bar' => false,
    'disable-admin-bar-comments-menu' => false,
    'disable-admin-bar-customize-menu' => false,
    'disable-admin-bar-edit-menu' => false,
    'disable-admin-bar-edit-site-menu' => false,
    'disable-admin-bar-howdy' => false,
    'disable-admin-bar-my-account-menu' => false,
    'disable-admin-bar-my-sites-menu' => false,
    'disable-admin-bar-new-content-menu' => false,
    'disable-admin-bar-recovery-mode-menu' => false,
    'disable-admin-bar-search-menu' => false,
    'disable-admin-bar-sidebar-toggle' => false,
    'disable-admin-bar-site-menu' => false,
    'disable-admin-bar-site-nav-menus' => false,
    'disable-admin-bar-site-themes' => false,
    'disable-admin-bar-site-widgets' => false,
    'disable-admin-bar-updates-menu' => false,
    'disable-admin-bar-wp-menu' => false,
    'disable-admin-dashboard-tab-help' => false,
    'disable-admin-dashboard-tab-screen-options' => false,
    'disable-admin-dashboard-welcome-panel' => false,
    'disable-admin-dashboard-widget-activity' => false,
    'disable-admin-dashboard-widget-browser-nag' => false,
    'disable-admin-dashboard-widget-incoming-links' => false,
    'disable-admin-dashboard-widget-plugins' => false,
    'disable-admin-dashboard-widget-primary' => false,
    'disable-admin-dashboard-widget-quick-press' => false,
    'disable-admin-dashboard-widget-recent-comments' => false,
    'disable-admin-dashboard-widget-recent-drafts' => false,
    'disable-admin-dashboard-widget-right-now' => false,
    'disable-admin-dashboard-widget-site-health' => false,
    'disable-admin-footer' => false,
    'disable-admin-tab-help' => false,
    'disable-admin-tab-screen-options' => false,
    'disable-admin-tools-erase-personal-data' => false,
    'disable-admin-tools-export' => false,
    'disable-admin-tools-export-personal-data' => false,
    'disable-admin-tools-import' => false,
    'disable-admin-tools-site-health' => false,
    'disable-asset-versioning' => false,
    'disable-auto-updates' => false,
    'disable-block-editor' => false,
    'disable-browser-check' => false,
    'disable-capital-p-dangit' => false,
    'disable-comments' => false,
    'disable-emojis' => false,
    'disable-frontend-wp-info' => false,
    'disable-php-version-check' => false,
    'disable-rest-api' => false,
    'disable-sitemaps' => false,
    'disable-smilies' => false,
    'disable-taxonomy-category' => false,
    'disable-taxonomy-post-format' => false,
    'disable-taxonomy-post-tag' => false,
    'disable-trackbacks' => false,
    'disable-update-notices' => false,
    'disable-xmlrpc' => false,
]);
